-- ============================================================
-- 1. CUSTOMERS
-- ============================================================

CREATE TABLE IF NOT EXISTS customers (
    customer_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    phone           VARCHAR(30),
    city            VARCHAR(100),
    country         VARCHAR(100) DEFAULT 'Indonesia',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 2. STORES
-- ============================================================

CREATE TABLE IF NOT EXISTS stores (
    store_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name      VARCHAR(150) NOT NULL,
    city            VARCHAR(100) NOT NULL,
    province        VARCHAR(100),
    country         VARCHAR(100) NOT NULL DEFAULT 'Indonesia',
    opened_date     DATE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 3. CATEGORIES
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
    category_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name   VARCHAR(100) NOT NULL UNIQUE,
    description     TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 4. SUPPLIERS
-- ============================================================

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name   VARCHAR(150) NOT NULL,
    contact_name    VARCHAR(150),
    email           VARCHAR(255),
    country         VARCHAR(100),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================
-- 5. PRODUCTS
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
    product_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     BIGINT NOT NULL,
    supplier_id     BIGINT NOT NULL,
    product_name    VARCHAR(200) NOT NULL,
    sku             VARCHAR(50) NOT NULL UNIQUE,
    cost_price      NUMERIC(12, 2) NOT NULL CHECK (cost_price >= 0),
    selling_price   NUMERIC(12, 2) NOT NULL CHECK (selling_price >= 0),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),

    CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id)
);


-- ============================================================
-- 6. ORDERS
-- ============================================================

CREATE TABLE IF NOT EXISTS orders (
    order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     BIGINT NOT NULL,
    store_id        BIGINT NOT NULL,
    order_date      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_status    VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    payment_method  VARCHAR(30) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_orders_store
        FOREIGN KEY (store_id)
        REFERENCES stores(store_id),

    CONSTRAINT chk_order_status
        CHECK (order_status IN (
            'PENDING',
            'COMPLETED',
            'CANCELLED',
            'REFUNDED'
        )),

    CONSTRAINT chk_payment_method
        CHECK (payment_method IN (
            'CASH',
            'DEBIT_CARD',
            'CREDIT_CARD',
            'E_WALLET'
        ))
);


-- ============================================================
-- 7. ORDER ITEMS
-- ============================================================

CREATE TABLE IF NOT EXISTS order_items (
    order_item_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL CHECK (quantity > 0),

    -- Snapshot prices at transaction time.
    -- This is important because product prices can change.
    unit_price      NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    unit_cost       NUMERIC(12, 2) NOT NULL CHECK (unit_cost >= 0),
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0
                    CHECK (discount_amount >= 0),

    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_products_category_id
    ON products(category_id);

CREATE INDEX IF NOT EXISTS idx_products_supplier_id
    ON products(supplier_id);

CREATE INDEX IF NOT EXISTS idx_orders_customer_id
    ON orders(customer_id);

CREATE INDEX IF NOT EXISTS idx_orders_store_id
    ON orders(store_id);

CREATE INDEX IF NOT EXISTS idx_orders_order_date
    ON orders(order_date);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
    ON order_items(order_id);

CREATE INDEX IF NOT EXISTS idx_order_items_product_id
    ON order_items(product_id);


-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


DROP TRIGGER IF EXISTS trg_customers_updated_at ON customers;
CREATE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


DROP TRIGGER IF EXISTS trg_stores_updated_at ON stores;
CREATE TRIGGER trg_stores_updated_at
BEFORE UPDATE ON stores
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


DROP TRIGGER IF EXISTS trg_categories_updated_at ON categories;
CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


DROP TRIGGER IF EXISTS trg_suppliers_updated_at ON suppliers;
CREATE TRIGGER trg_suppliers_updated_at
BEFORE UPDATE ON suppliers
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


DROP TRIGGER IF EXISTS trg_products_updated_at ON products;
CREATE TRIGGER trg_products_updated_at
BEFORE UPDATE ON products
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


DROP TRIGGER IF EXISTS trg_order_items_updated_at ON order_items;
CREATE TRIGGER trg_order_items_updated_at
BEFORE UPDATE ON order_items
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();


-- ============================================================
-- CDC SUPPORT
-- ============================================================
-- FULL replica identity makes old row values available for
-- UPDATE/DELETE CDC events.
--
-- This is useful for demonstrating CDC with Airbyte.
-- ============================================================

ALTER TABLE customers REPLICA IDENTITY FULL;
ALTER TABLE stores REPLICA IDENTITY FULL;
ALTER TABLE categories REPLICA IDENTITY FULL;
ALTER TABLE suppliers REPLICA IDENTITY FULL;
ALTER TABLE products REPLICA IDENTITY FULL;
ALTER TABLE orders REPLICA IDENTITY FULL;
ALTER TABLE order_items REPLICA IDENTITY FULL;